export declare const ACTIONS: {
    CREATE_EXTERNAL_ACCOUNT: string;
    CREATE_CONTRACT_ACCOUNT: string;
    NODE_REGISTERED: string;
    MUTATE_CONTRACT_DATA: string;
    MINING_REWARD: string;
    INSTANT_MESSAGE: string;
    TRANSACTION_EXTERNAL_ACCOUNT: string;
    TRANSACTION_CONTRACT_ACCOUNT: string;
};
